agent:
  description: Custom AI agent with flexible configuration
  enable_memory: true
  max_conversation_turns: 50
  name: My Custom Agent
  system_prompt: You are a helpful AI assistant. Customize this prompt for your specific
    use case.
api:
  cors_origins:
  - '*'
  host: 127.0.0.1
  port: 8001
  reload: false
  workers: 1
bedrock:
  cache_prompt: null
  cache_tools: null
  guardrail_id: null
  guardrail_trace: enabled
  guardrail_version: null
  max_tokens: 4096
  model_id: anthropic.claude-3-haiku-20240307-v1:0
  region_name: us-west-2
  stop_sequences: null
  streaming: true
  temperature: 0.7
  top_p: null
environment:
  debug: true
  enable_metrics: true
  log_level: INFO
  max_concurrent_connections: 100
  name: development
  rate_limit_requests: 60
mcp:
  auto_discover: true
  connection_timeout: 30
  default_transport: stdio
  discovery_paths:
  - ~/.mcp/servers
  - /usr/local/mcp/servers
  servers: {}
