a2a:
  agent_id: writer_agent
  peers:
  - agent_id: assistant_agent
    endpoint: http://localhost:8120
  - agent_id: researcher_agent
    endpoint: http://localhost:8121
  server_port: 8122
agent:
  description: Content creation and writing specialist
  enable_memory: true
  max_conversation_turns: 50
  name: Writer Agent
  system_prompt: 'You are a professional writer and content specialist focusing on:

    - Technical documentation and guides

    - Marketing copy and communications

    - Creative writing and storytelling

    - Content optimization and editing


    Create engaging, well-structured content adapted to your audience.'
api:
  cors_origins:
  - '*'
  host: 127.0.0.1
  port: 8022
  reload: false
  workers: 1
bedrock:
  cache_prompt: null
  cache_tools: null
  guardrail_id: null
  guardrail_trace: enabled
  guardrail_version: null
  max_tokens: 6144
  model_id: anthropic.claude-3-haiku-20240307-v1:0
  region_name: us-west-2
  stop_sequences: null
  streaming: true
  temperature: 0.8
  top_p: null
environment:
  debug: true
  enable_metrics: true
  log_level: INFO
  max_concurrent_connections: 100
  name: development
  rate_limit_requests: 60
mcp:
  auto_discover: true
  connection_timeout: 30
  default_transport: stdio
  servers: {}
